-- 创建 SYS_CUSTOMER 表
CREATE TABLE IF NOT EXISTS SYS_CUSTOMER (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    DEFAULT_TENANT_ID BIGINT DEFAULT 0 NOT NULL,
    USERNAME VARCHAR(50) NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    PASSWORD_SLAT VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(100),
    STATUS VARCHAR(12) DEFAULT 'ACTIVE' NOT NULL,
    VERSION BIGINT DEFAULT 0 NOT NULL,
    CREATED_AT TIMESTAMP,
    CREATED_BY BIGINT,
    UPDATED_AT TIMESTAMP,
    UPDATED_BY BIGINT,
    DELETED BOOLEAN DEFAULT FALSE,
    DELETED_AT TIMESTAMP,
    DELETED_BY BIGINT DEFAULT 0,
    TENANT_ID BIGINT DEFAULT 0
);

-- 创建唯一索引
CREATE UNIQUE INDEX IF NOT EXISTS UK_SYS_CUSTOMER_USERNAME ON SYS_CUSTOMER(USERNAME);
CREATE UNIQUE INDEX IF NOT EXISTS UK_SYS_CUSTOMER_EMAIL ON SYS_CUSTOMER(EMAIL);

-- 创建普通索引
CREATE INDEX IF NOT EXISTS IDX_SYS_CUSTOMER_USERNAME ON SYS_CUSTOMER(USERNAME);
CREATE INDEX IF NOT EXISTS IDX_SYS_CUSTOMER_EMAIL ON SYS_CUSTOMER(EMAIL);

-- 插入测试数据
INSERT INTO SYS_CUSTOMER (ID, USERNAME, PASSWORD_HASH, PASSWORD_SLAT, EMAIL, STATUS, DEFAULT_TENANT_ID, CREATED_AT, CREATED_BY) 
VALUES (1, 'test_admin', 'admin123', 'salt', 'test@example.com', 'ACTIVE', 1, CURRENT_TIMESTAMP(), 1);

INSERT INTO SYS_CUSTOMER (ID, USERNAME, PASSWORD_HASH, PASSWORD_SLAT, EMAIL, STATUS, DEFAULT_TENANT_ID, CREATED_AT, CREATED_BY) 
VALUES (2, 'test_user', 'user123', 'salt', 'user@example.com', 'ACTIVE', 1, CURRENT_TIMESTAMP(), 1);

INSERT INTO SYS_CUSTOMER (ID, USERNAME, PASSWORD_HASH, PASSWORD_SLAT, EMAIL, STATUS, DEFAULT_TENANT_ID, CREATED_AT, CREATED_BY) 
VALUES (3, 'locked_user', 'user123', 'salt', 'locked@example.com', 'LOCKED', 1, CURRENT_TIMESTAMP(), 1);
